### PR TITLE
Test Go mod bump

### PR DESCRIPTION
**Pull request by macedogm**
This PR adds tests for Go mod dependencies bump:

1. Enable the bump of Go dependencies.
2. Set Go version constraint to the current used version in Rancher.
3. Uses Renovate non-slim image that contains the Go binary needed for executing `go mod tidy`.
4. Add RKE1 code as example of Go dependencies to bump. This was separated on a second commit, since only the first commit is the important for enabling Go mod bumps.

### CODE REVIEW

**Review by superseb — COMMENTED** [review]
- Is it intentional to have certain global things specific to this repository? constraints, postUpdateOptions and osvVulnerabilityAlerts (which seems to be unrelated to golang) seem to be candidates for global configuration
- empty `      "matchManagers": ["gomod"]` seems unneeded?
- slim image uses sidecar to run Go, see https://github.com/sebtestorg2/bro/pull/22#issuecomment-1340363534. Is it a hard requirement to not use the slim for `go mod tidy`?
- What version of Renovate was this configuration tested with as v36 is introducing new configuration from <v36 which we are currently using
-

**Comment by pjbgf** [comment]
I am not very versed on renovate, so I don't have much to add about the first commit.

On the second commit, I wonder whether we would benefit by having a simpler example that focuses just on our key use cases:
- Simple Go Project
- Dockerfile
- Makefile 
- Multi modules Workspaces (not sure how common this is across our code base)

**Comment by superseb** [comment]
Managers are enabled using `enabledManagers` but as we set this in repo specific config, you don't need to do anything for it here as all managers are enabled in this repository.

Can you share the workflow run for ```Strange, because during the tests (I referenced our [rancher/renovate-config](https://github.com/rancher/renovate-config)) go mod tidy wasn't being executed. If I missed something and it works with slim, then we can revert this specific change.``` ?

I thought they added the slim config option as well but it seems its only `renovate-version` since v36.0.0 to set the Renovate version although the slim config option seems to be undocumented at the GitHub Action repo itself. I would still like to keep slim as it quite a bit smaller and the workflow runs should be faster. But obviously we need the functionality so we can switch if needed.

**Comment by macedogm** [comment]
Closing this PR, since Go mod bumps are correctly working in `rancher/rancher`.

**Pull request closed without merging**
